### ISSUE TITLE
LOCATE FACE+16gr

### ISSUE THREAD

**Issue by ozguraytekin** [robhagemans/pcbasic#71] opened 2018-04-11 19:22 UTC
![untitled](https://user-images.githubusercontent.com/553570/38638389-681966f4-3dce-11e8-9237-e47c549c47b0.jpeg)

**Comment by robhagemans** [comment] 2018-04-12 18:44
This issue has been resolved in version 1.2.13, please update.

Duplicate of #64

**Closed** 2018-04-16 07:53 UTC
Labels: duplicate
