### ISSUE TITLE
cannot loading file even path exist

### ISSUE THREAD

**Issue by naumanumer** [robhagemans/pcbasic#8] opened 2016-09-26 10:10 UTC
version: 15.8.10
platform: win 10 (64 bit)

getting `Path not found` when calling pcbasic with `--run="D:\path\to\a.BAS"` but the `a.bas` is present here. i also tried `/` and `\\`  instead of `\`. but getting same error.

when i call pcbasic**.exe** with same parameters the pcbasic just run and than closes automatically without displaying any message

**Comment by robhagemans** [comment] 2016-09-26 13:49
Sorry, I can't reproduce this issue - this works correctly for me. What are the exact command lines you use?

**Comment by robhagemans** [comment] 2016-09-26 13:50
Note that the behaviour with the `.exe` is expected - you will never see output on the command line if you call the `exe` directly as it is a GUI executable. Always use the `.com` from the command line.

**Comment by naumanumer** [comment] 2016-09-26 16:04
file path: "D:\Documents\Nauman Umer\New folder\electron-quick-start\PC-BASIC\a.BAS" (copied from explorer) file is actually empty.
pcbasic and current command line path: "C:\Program Files (x86)\PC-BASIC" (copied from dos)
here is the result of some commands written in dos
```
C:\Program Files (x86)\PC-BASIC>type "D:\Documents\Nauman Umer\New folder\electron-quick-start\PC-BASIC\a.BAS"

C:\Program Files (x86)\PC-BASIC>pcbasic --run="D:\Documents\Nauman Umer\New folder\electron-quick-start\PC-BASIC\a.BAS"
ERROR: Path not found

C:\Program Files (x86)\PC-BASIC>
```
i have another file in the same directory file path: "D:\Documents\Nauman Umer\New folder\electron-quick-start\PC-BASIC\art.BAS"

tried this file

```
C:\Program Files (x86)\PC-BASIC>type "D:\Documents\Nauman Umer\New folder\electron-quick-start\PC-BASIC\a.BAS"

C:\Program Files (x86)\PC-BASIC>type "D:\Documents\Nauman Umer\New folder\electron-quick-start\PC-BASIC\art.BAS"
¼Å The IBM Personal Computer Art ╢Å Version 1.10 (C)Copyright IBM Corp 1981, 1982 H└Å Licensed Material - Program Property of IBM l╩Å Author - Glenn Stuart Dardick ╧ù SEG:  ÿ j, ô╘SAMPLES$ τ "NO" ¥▐ë ≥ ▓ΦSAMPLES$ τ "YES" ▀≥╔ ▌:╚ ,:┐ ,,:á (:└:╩ ,:æ "IBM" ⁿ╩ ,,:æ "Personal Computer" /┐ 
,:╩ 
,
C:\Program Files (x86)\PC-BASIC>pcbasic --run="D:\Documents\Nauman Umer\New folder\electron-quick-start\PC-BASIC\art.BAS"
[pcbasic executes the file]
C:\Program Files (x86)\PC-BASIC>
```
So, i think this error is only for empty files.
a.bas is also produced from pcbasic. file is attached to this comment as zip.
[a.zip](https://github.com/robhagemans/pcbasic/files/493526/a.zip)

**Comment by robhagemans** [comment] 2016-09-26 16:29
Thanks, I can reproduce this now with an empty file and will investigate. See also my comment in https://github.com/robhagemans/pcbasic/issues/7 - it seems these two issues are related.

**Comment by robhagemans** [comment] 2016-09-26 16:48
Empty file bug is fixed - will be in next release. Thanks!

**Closed by robhagemans** 2016-09-26 16:48 UTC
