### ISSUE TITLE
Unexplainable Windows crash

### ISSUE THREAD

**Issue by ScttB** [robhagemans/pcbasic#48] opened 2017-10-26 18:10 UTC
![image](https://user-images.githubusercontent.com/6832106/32068887-672710cc-ba3c-11e7-882f-621d740b5107.png)
I'm not exactly sure what causes this because it straight-up crashes without any error, but this is the program i'm using. It might have to do with drawing and using `play "P8"` to wait between screen updates.
```
10 screen 1: cls: line (0,0)-(320,200),0,bf
15 let kee$=inkey$
20 locate 23,1:print "loading... plz wait - press q to quit"
30 for x=100 to 0 step -1
40 let c=c+1
50 if c>3 then: let c=0
60 line (x,x)-(0,0),c,bf
70 next
80 if (kee$="q") or (kee$="Q") then: cls: end
80 play "P8"
90 goto 15
```
Before, it crashed a few seconds after starting, and with this slightly-different code (which is different because PC-BASIC crashed so I couldn't recover my program), it now crashes when I press a key.
I couldn't find any log files in `C:\Program Files (x86)\PC-BASIC` or `%USERPROFILE%`, so good luck figuring out why exactly this causes a crash.

**Comment by robhagemans** [comment] 2017-11-28 10:10
Hi, are you using 64-bit Windows? These random crashes are a known issue on that platform, previously discussed on the forum. Unfortunately I can't reproduce it - it seems to occur only on some installations - so I have so far been unable to find the cause, let alone a fix or workaround. You may want to try the development release that uses SDL2, as I think the crash arises in Pygame.

**Comment by ScttB** [comment] 2017-12-07 19:48
@robhagemans Yes.

**Comment by robhagemans** [comment] 2017-12-25 10:28
See here for earlier (unsuccessful) attempts to narrow down this issue:
https://sourceforge.net/p/pcbasic/discussion/bugs/thread/27eccbdb/

I'm going to keep this issue open to document further progress, if any, on this issue. 

However I think the solution will have to come from either an upstream fix in PyGame or from a replacement of PyGame by SDL2. Unfortunately I can't recreate the issue to investigate, as it does not occur on my Windows setups, so I don't know if it really is a PyGame bug and if so, what causes it.

**Comment by robhagemans** [comment] 2018-01-14 11:16
Hi @ScttB, if you have a chance could you check this on the latest release?

https://github.com/robhagemans/pcbasic/releases/tag/15.08.12

This includes an updated Pygame 1.9.3. While I can't find anything in the changelog that looks related to this issue, it's just about possible that it does away with it.

**Comment by robhagemans** [comment] 2018-02-28 19:50
I'm going to close this on the assumption the issue was solved by the newer Pygame.
If the crashes still occur, please re-open or open a new issue. Thanks!

**Closed by robhagemans** 2018-02-28 19:50 UTC
Labels: bug
