### ISSUE TITLE
Crash in PC BASIC v1.2 on clipboard copy (?)

### ISSUE THREAD

**Issue by harshyo** [robhagemans/pcbasic#180] opened 2022-03-01 15:35 UTC
I just got a pop up window and saw that it was a bug and it was told to report so I reported and I have also given the picture.

**Notes**

PC-BASIC version:  1.2.14
Operating system version:  Windows 11
![harsh](https://user-images.githubusercontent.com/100706316/156198461-7132d60b-0095-420d-939d-d628e25b05cd.png)

![harsh](https://user-images.githubusercontent.com/100706316/156198408-2b52b138-7ae9-4f20-aa91-e80743b0cbb7.png)

**Comment by rbergen** [comment] 2022-03-10 20:35
You may want to try again using PC-BASIC 2.0.4. Issues found in 1.x versions of PC-BASIC are less likely to get much attention, now that 2.x has been out for a number of years.

**Comment by robhagemans** [comment] 2022-06-22 20:08
For reference, looks like this is something happening when copying text to the clipboard. From the context it's not clear exactly what, unfortunately.

**Comment by rbergen** [comment] 2022-06-23 08:47
@robhagemans This question may be slightly out of context, and I don't mean to be dismissive to bug report let alone its reporter, but is there a specific reason you're still supporting v1.2?

**Comment by robhagemans** [comment] 2022-06-23 10:10
I'm not, or at least not really. I mostly just tagged it so I know not to
prioritize it...

**Comment by rbergen** [comment] 2022-06-23 10:15
Yep, that's the other reason to add the flag. :)

**Comment by robhagemans** [comment] 2022-06-25 13:45
Closing as I can't reproduce on the latest version v2.0.4. If you run into this crash again in the latest version, please feel free to reopen or log a new issue.

**Closed by robhagemans** 2022-06-25 13:45 UTC
Labels: bug, v1.2 only
