### ISSUE TITLE
PRINT creates CR when at screen edge, but it should not.

### ISSUE THREAD

**Issue by JDoucette** [robhagemans/pcbasic#168] opened 2021-11-17 05:21 UTC
## Bug report

**Problem**
If `PRINT` prints data that touches the screen edge, PC-BASIC creates a CR, but GW-BASIC does not.

**Steps**
1.  Run the program in PC-BASIC (1.2 or 2.0, Tandy mode or not)
2.  See there is a space between LAST LINE and the previous 40-char width PRINT.
3.  There should be no space.  

**Program**
```
10 WIDTH 40
20 PRINT "12345678901234567890123456789012345678"
30 PRINT "123456789012345678901234567890123456789"
40 PRINT "1234567890123456789012345678901234567890"
50 PRINT "LAST LINE"
```

**Crash log**
None.

**Notes**
PC-BASIC version: 1.2 and 2.0  
Operating system version:  Windows 10

![PC-BASIC-1 2](https://user-images.githubusercontent.com/1381969/142139718-d40e8c45-ed71-447b-abbd-deebdaef6c9a.PNG)
![PC-BASIC-2 0](https://user-images.githubusercontent.com/1381969/142139725-73fc0a9b-6463-4de9-b0fc-a177e3623d15.PNG)
![TANDY-GW-BASIC-3 2-DOSBOX](https://user-images.githubusercontent.com/1381969/142139726-458da012-a94a-401c-af18-ab092d5f9af0.PNG)

**Comment by rbergen** [comment] 2021-11-30 07:03
I think this is caused by [this line in `/pcbasic/basic/devices/formatter.py`](https://github.com/robhagemans/pcbasic/blob/0e0a758d7dca91daf6bfe8c6111218f46967a9ae/pcbasic/basic/devices/formatter.py#L42) and the one that follows it.

They specifically add a _second_ line break if a newline is requested and a character has been printed in the last column on the screen; that being indicated by `Formatter._console.overflow` being `True`. Removing the two lines would fix this. However, it looks to me like they were deliberately added to insert the extra newline, and I don't know what removing the lines would break.

**Comment by rbergen** [comment] 2021-11-30 07:31
After giving it some thought, it may be that the intended functionality would be achieved by replacing [lines 41](https://github.com/robhagemans/pcbasic/blob/0e0a758d7dca91daf6bfe8c6111218f46967a9ae/pcbasic/basic/devices/formatter.py#L41) to 44, that being
```python
        if newline:
            if self._console and self._console.overflow:
                self._output.write_line()
            self._output.write_line()
```
with the following code:
```python
        if newline or (self._console and self._console.overflow):
            self._output.write_line()
```

**Comment by robhagemans** [comment] 2021-11-30 07:56
Any change to this is really going to need a lot of testing, this is a
fundamental part of the code and everything depends on everything.
Unfortunately (1) a lot of this is difficult to implement as an automated
test so needs to run through a number of example programs and be checked
visually and (2) not all tests pass in any case .(iirc there's 28 test
failures) so you need great care to avoid regression...

**Comment by rbergen** [comment] 2021-11-30 08:02
This is exactly why I'm sharing thoughts and not opening a PR for this. Yet. :)

**Comment by rbergen** [comment] 2021-12-01 08:18
I was wondering, is there any text (documentation, existing test code, ...) I could read that would tell me what tests would need to be performed to verify the correct operation of screen output routines?

**Comment by robhagemans** [comment] 2021-12-01 14:32
Not really, sorry... There are the automated tests however in he test
directory that cover at least part of what's needed

**Comment by rbergen** [comment] 2021-12-01 16:19
I understand. I'll have to give this some thought. One the one hand I'm very willing to put in the time and effort to improve PC-BASIC, but I really do not want to introduce new and hard-to-diagnose bugs in such a critical part of the application.

**Comment by robhagemans** [comment] 2021-12-01 16:52
Yes, I'll have a look at it anyway, but I'm not sure when.

At the very least I'll turn the bug example into an additional test and see
if your proposed change breaks anything else I know of

**Comment by rbergen** [comment] 2021-12-03 21:05
I've done some exploratory testing with the change I suggested in place, and so far everything I've tried (line breaks, line editing, line deletion, etc.) works as I would expect it.

**Comment by robhagemans** [comment] 2022-06-25 15:06
So, if I run this in my copy of DOSBox I *do* actually get the additional newline. Which probably explains why the specific line in the code is there. Has anyone tried this on real hardware?

**Comment by robhagemans** [comment] 2022-06-25 15:14
This is what I see in VirtualBox, MS-DOS 6.22 with GW-BASIC 3.23:

![vbox_msdos_gwbasic_extra_cr](https://user-images.githubusercontent.com/7723154/175779670-2f02a270-7c99-4a02-b1f7-1398bdca43eb.png)

A test on real hardware would be more authoritative, but as it stands I'm inclined to think this is not a bug in PC-BASIC but in that version of DOSBox. Unless this is dependent on the particular video card?

**Comment by rbergen** [comment] 2022-06-25 15:26
That's interesting, indeed. Personally, I'm happy to reject my own PR because of the VirtualBox evidence. Just to get my facts straight, what version of DOSBox are you using?

**Comment by robhagemans** [comment] 2022-06-25 15:30
0.74, but they all seem to have that version number...

**Comment by DualBrain** [comment] 2022-06-25 16:11
PRINT will print a new line, according to documentation, if the last character is at the edge of the screen... unless, of course, you use either a semi-colon, a comma (which would appear to be a new line, but isn't), a spc(0) (pretty much the same as a semi-colon or a tab(< screen width).

**Comment by DualBrain** [comment] 2022-06-25 16:13
To quote...

> If a comma, semicolon, or SPC or TAB function ends an expression list, the next PRINT statement begins printing on the same line, accordingly spaced. If the expression list ends without a comma, semicolon, or [SPC](https://github.com/DualBrain/bsharp/wiki/SPC) or [TAB](https://github.com/DualBrain/bsharp/wiki/TAB) function, a carriage return is placed at the end of the lines (BASIC places the cursor at the beginning of the next line).

> A carriage return/line feed is automatically inserted after printing width characters, where width is 40 or 80, as defined in the [WIDTH](https://github.com/DualBrain/bsharp/wiki/WIDTH) statement. This results in two lines being skipped when you print exactly 40 (or 80) characters, unless the PRINT statement ends in a semicolon.

**Comment by rbergen** [comment] 2022-06-25 17:06
> A carriage return/line feed is automatically inserted after printing width characters, where width is 40 or 80, as defined in the WIDTH statement. This results in two lines being skipped when you print exactly 40 (or 80) characters, unless the PRINT statement ends in a semicolon.

I've now found various digital copies of the GW-BASIC user manuals that say exactly that. I'm sufficiently convinced that PC-BASIC's current behaviour is in fact correct. I'll close #170.

**Comment by robhagemans** [comment] 2022-06-29 20:44
Closing as not a bug. Added the example code in this issue as a test case, commit 2f77b44b

**Closed by robhagemans** 2022-06-29 20:44 UTC
Labels: awaiting confirmation
