### ISSUE TITLE
pcbasic breaks neovim layout and colors on MacOS Mojave

### ISSUE THREAD

**Issue by niloct** [robhagemans/pcbasic#129] opened 2020-11-22 13:02 UTC
## Bug report
pcbasic breaks neovim layout and colors on MacOS Mojave

**Problem**
There are two issues I've identified (both are screencasted, see the attachment gif):

1. When you execute pc-basic, exits and open neovim, status bar color is changed.
2. When you execute pc-basic, hits enter till you have to redraw the screen (i.e. the cursor goes below viewport), it totally breaks status bar position (it's "vertically centered" then...)
 
**Steps**
See attaching gif.

**Program**
No need to code anything.

**Notes**

PC-BASIC version: 2.0.3  
Operating system version: MacOs Mojave
Neovim version: v0.4.3 
![bug_neovim_pcbasic](https://user-images.githubusercontent.com/1529383/99904434-80630400-2ca9-11eb-843f-59b7b0d169ee.gif)
 
Thanks for your attention.

**Comment by niloct** [comment] 2020-11-28 12:50
Hello anyone ?

**Comment by niloct** [comment] 2020-11-28 12:59
For issue 1., the culprit is this line:

https://github.com/robhagemans/pcbasic/blob/6807f35bb5f72ddf993fb11ed9c9336f37dcf612/pcbasic/compat/posix_console.py#L414

If you comment it then the color is not changed when running nvim after closing pc-basic.

**Comment by robhagemans** [comment] 2020-11-29 09:41
Hi thanks, what terminal emulator are you using to run `bash` in?

**Comment by niloct** [comment] 2020-11-29 13:16
Hello!

I'm using iterm2.

Em dom, 29 de nov de 2020 06:41, Rob Hagemans <notifications@github.com>
escreveu:

**Comment by robhagemans** [comment] 2020-11-29 20:24
OK, that explains - in Terminal.app I couldn't reproduce the issue. I'll try it out with iTerm2 at some point, though I won't be able to support/test every single terminal emulator.

How have you installed PC-BASIC by the way? I note you don't have SDL2 which should be included in the standard installs. Normally if you start `./pc-basic` (and SDL2 is available) you should get a separate window which also supports graphics - the terminal interface you're currently getting is just a fallback.

**Comment by niloct** [comment] 2020-11-30 15:05
I haven't :)

I've cloned the repo and ran `./pc-basic`.

**Comment by robhagemans** [comment] 2021-11-12 07:28
At the moment I am unable to release working MacOS packages and this is unlikely to be resolved unless a Mac user with a recent version of the OS steps up as package maintainer, so I'm going to close this issue as I see no path to its resolution.

**Closed by robhagemans** 2021-11-12 07:28 UTC
