### ISSUE TITLE
Windows 10 "Fall Creators Edition" PC-BASIC Problems...

### ISSUE THREAD

**Issue by LindaLatte** [robhagemans/pcbasic#63] opened 2018-02-28 18:59 UTC
Wednesday February 28 2018, 10:44 AM

Hi All,
Please be aware that PC-BASIC does NOT either "install" or "print" using the _LATEST_ version of Win 10 from M$ (Microsoft). I'm referring to: "Win 10 Home, Version 1709, and OS Build 16299.192." This is TRUE even if it has "python" installed and working. Now, it is POSSIBLE, but I have no way to verify, that PC-BASIC _might_ work on earlier Win 10 versions? I have no way to determine THAT. Despite his BEST efforts, and he really tried _HARD_, Rob Hagenmans, over a several week period, was unable to solve all my issues. A few of the problems are:  #1, Your .bas files will NOT be found where the documentation SAYS they are located, AND, #2, you will NOT be able to print using the LPT1 cmnd. Rob _DID_ find my .bas files, finally, after weeks, but not where they were supposed to be. There MAY be OTHER problems too. I dunno. I gave up trying to use PC-BASIC after weeks of frustration. I really NEED pcbasic.exe and _WISH_ it would work for me. If anyone finds a FIX for my Win 10, please e-mail me?
Thank you,
Linda

Wednesday February 28 2018, 1:40 PM
Apologies, instead of referring to printing as  "using LPT1," I should have said, "print by accessing the LPT1: device," as stated in the documentation. The latest Windows 10 "Fall Creators Edition" will not let PC-BASIC access the the PC's printer.  :( It would be GREAT to find out WHY not?  Soon, others, if any, using Win 10 will not be able to print simply because, unlike the "old days," you cannot stay with an OS as long as you want. M$, (Microsoft), now FORCEFULLY up-dates Win 10 whether you like it or not. If there are PC-Basic Users of Win 10, they will not be using it much longer. M$ will, guaranteed, FORCE them to "up-grade" to the new version I'm now stuck with.  :( Sad to say, but true. :(  I'm sure everyone prays that a solution to this Win 10 issue is forthcoming.

**Comment by robhagemans** [comment] 2018-02-28 19:47
From other reports and own experience, PC-BASIC has been known to install and print on several installations of Windows 10 and so far this issue has not been reproducible on other installs.

Note also that there is no `LPT1` command in PC-BASIC.

However if anyone has experienced similar issues on Windows 10 (in particular, with files being stored in `%LocalAppData%\VirtualStore`) , please report them here - it could help solve any issue that may underly this. Thanks!

**Comment by robhagemans** [comment] 2018-03-07 08:29
Since I cannot replicate this and there has been no further activity, I'm closing this issue.

If more people experience installation problems on Windows 10, or have files being unexpectedly stored in `%LocalAppData%\VirtualStore`: please reopen this issue, or open a new issue as appropriate.

In general, when reporting bugs, please provide detailed information about:
- the _exact_ steps you took, so that they can be replicated by someone else.  
- the result you expected 
- what happened instead of the expected result
- full text or screenshots of any error messages you encounter

Without this, I'm unlikely to be able to fix the problem.

Thanks!
Rob

**Closed by robhagemans** 2018-03-07 08:29 UTC
