### ISSUE TITLE
Leading padding in printing output

### ISSUE THREAD

**Issue by squirrelhavoc** [robhagemans/pcbasic#13] opened 2016-12-12 19:00 UTC
When I output something simple by printing it with either "LPRINT" or printing a listing with "LLIST", each line gets padded with leading NULL 0's in text file output, and whitespace in printing output. The number of padded characters is increased with each new line printed (see attached file). Is this a bug, or a feature I don't understand?
[test_output.zip](https://github.com/robhagemans/pcbasic/files/646889/test_output.zip)

**Comment by robhagemans** [comment] 2016-12-12 19:24
That's another regression vs 15.08, thanks for reporting! 
Looks like some issue with the buffer stream. It's certainly not a feature (though some features of BASIC are very much like bugs...)

**Comment by robhagemans** [comment] 2016-12-12 19:54
This is fixed, fix will be included in next prerelease.

**Closed by robhagemans** 2016-12-12 19:54 UTC
