### ISSUE TITLE
cannot run program using run parameter

### ISSUE THREAD

**Issue by naumanumer** [robhagemans/pcbasic#7] opened 2016-09-26 10:01 UTC
version: 15.8.10
platform: windows 10 (64 bit)

getting following error when calling pcbasic with `--load="a.bas"`.
```
ERROR: Unhandled exception
Traceback (most recent call last):
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.__main__", line 164, in start_basic
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.__main__", line 316, in open_native_or_doe
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.devices", line 97, in open_file
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.disk", line 440, in open
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.disk", line 647, in open_diskfile
IOError: [Errno 22] Invalid argument
```

"a.bas" doesn't exist but i think it must raise `ERROR: Path not found` error as in previous verisons

**Comment by robhagemans** [comment] 2016-09-26 13:48
Sorry, I can't reproduce this issue - I get `ERROR: File not found` which I think is correct. What is the exact command line you use? Are you calling this directly from the command line or from another program?

**Comment by naumanumer** [comment] 2016-09-26 15:52
I am calling this directly form command line. the exact command is 

```
C:\Program Files (x86)\PC-BASIC>pcbasic --load="a.bas"
ERROR: Unhandled exception
Traceback (most recent call last):
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.__main__", line 164, in start_basic
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.__main__", line 316, in open_native_or_doe
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.devices", line 97, in open_file
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.disk", line 440, in open
  File "E:\branch1508\packaging\windows\build\installer\out00-PYZ.pyz\pcbasic.disk", line 647, in open_diskfile
IOError: [Errno 22] Invalid argument


C:\Program Files (x86)\PC-BASIC>
```

**Comment by robhagemans** [comment] 2016-09-26 16:26
If the file does not exist, on 32-bit nor 64-bit Windows 7 I get:

    Microsoft Windows [Version 6.1.7601]
    Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

    C:\Users\rob>"c:\Program Files (x86)\PC-BASIC\pcbasic" --load="a.bas"
    ERROR: File not found

    C:\Users\rob>"c:\Program Files (x86)\PC-BASIC\pcbasic.com" --load="a.bas"
    ERROR: File not found

    C:\Users\rob>"c:\Program Files (x86)\PC-BASIC\pcbasic.com" -v
    15.08.10

However, with an empty file (zero bytes) `a.bas` (as per your comment in the other thread) I do get the `Invalid argument` exception, which is a bug. I'll investigate - thanks for reporting!

**Comment by robhagemans** [comment] 2016-09-26 16:43
Empty file bug is fixed - will be in next release. Thanks!

**Closed by robhagemans** 2016-09-26 16:43 UTC
