### ISSUE TITLE
PLAY command failure

### ISSUE THREAD

**Issue by tonypdmtr** [robhagemans/pcbasic#107] opened 2019-11-08 23:36 UTC
The statement
PLAY "ML"
crashes the interpreter.

**Comment by robhagemans** [comment] 2019-11-09 06:40
Hi @tonypdmtr,
Which version of PC-BASIC do you use and what operating system? 
I cannot reproduce this crash on PC-BASIC 1.2.14 or PC-BASIC 2.0.2.

If you use an older version, could you please upgrade and try again?

Thanks,
Rob

**Comment by tonypdmtr** [comment] 2019-11-09 08:36
I just installed it with pip install pcbasic (under Python 3.8) so it's got to be the latest (v2.0.2)?
Win64 machine.
![bug](https://user-images.githubusercontent.com/11968823/68525679-b6bb2480-02dc-11ea-8667-dd59eabeb046.jpg)

**Comment by tkchia** [comment] 2019-11-09 16:55
Hello @tonypdmtr,

Me, I cannot reproduce the crash either, simply by running a `PLAY"ML"` statement.  Were there any statements before or after the `PLAY"ML"` in the BASIC program you were running?

Thank you!

**Comment by tonypdmtr** [comment] 2019-11-09 22:55
I ran an old program that had this command.  But, then I tried the command all by itself and the crash still happens.  So, just PLAY "ML" is enough to show the problem in my system.

**Comment by robhagemans** [comment] 2019-11-10 12:08
Thanks for the screenshot which has a lot of the information I need. There
may be something that changed in how Python 3.8 handles generators and
StopIteration, I think I still have been using Python 3.6 or 3.7 so I will
have to investigate. I'll update when I know more.

**Comment by jsanjose** [comment] 2020-04-04 11:38
Same crash. Also on Python 3.8.

Any advance on this bug?

**Comment by robhagemans** [comment] 2020-09-22 07:02
This is now fixed on the `develop` branch, thanks for reporting

**Closed by robhagemans** 2020-09-22 07:02 UTC
