### ISSUE TITLE
PC-BASIC 2 graphics do not update between PSET calls

### ISSUE THREAD

**Issue by JDoucette** [robhagemans/pcbasic#166] opened 2021-11-14 01:41 UTC
## Bug report
See: https://www.youtube.com/watch?v=9J9DtrcoDXc

**Problem**

**Steps**

1. run below program 
2. expect graphics updates to happen in real-time
3. they do not
4. add A$=INKEY$ inside the loop, and it works

**Program**
```
10 SCREEN 1
20 FOR Y=0 TO 199:FOR X=0 TO 319
30 PSET(X,Y),INT(RND*4)
40 NEXT X:NEXT Y
```

**Notes**

PC-BASIC version:  2.0.4
Operating system version: Windows 10

**Comment by JDoucette** [comment] 2022-02-21 20:52
This also occurs in text mode.
```
5 SCREEN 0,0,0:WIDTH 80:CLS
10 I!=I!+.1:J#=J#+.1#:LOCATE 1,1:PRINT I!;J#;(I!-J#):GOTO 10
```
Simple program that adds 0.1 repeatedly and draws the results.
The screen should be updating blazingly fast.
But it stalls, and updates randomly.

_p.s.  Unrelated to the bug: This reminiscent of a very old program I made as a kid where I was amazed that adding 0.1 over and over again would not result in accurate results, and furthermore, you could watch the velocity of the accumulative error, and the acceleration changes as it would jump into positive flow, then negative flow._

**Comment by robhagemans** [comment] 2022-06-30 21:17
Thanks for reporting, fixed with issue 8d1ae6f0. The fix is to call `time.sleep(0)` twice. I have no idea why this works or more precisely, why it is necessary.

**Comment by theruler** [comment] 2022-08-23 20:31
The issue is still present when using more than one core due to, I think, python's GIL.
If you set the affinity to one or two cpu the bug is gone and the screen updates fast without the A$=INKEY$ workaround.
But if you leave default (ALL) CPU affinity, the update is "choppy" and have to use A$.

i76700 - 1 CPU, 4 CORES, 8 THREADS
Win 11 - pcbasic 2.0.6

**Comment by robhagemans** [comment] 2022-08-24 12:40
I'm sorry @theruler can you please explain what you're doing? What is "affinity"? I do not see this problem anymore on my machine (which is also multi-core) so would need more information to be able to reproduce.

**Comment by theruler** [comment] 2022-08-24 13:11
Yes, sure.
Tried on three modern multicore PC with windows (2x win10 and 1x win11):
If I paste the code on PCBASIC 2.0.6 without the A$=INKEY$ workaround:
```
5 SCREEN 0,0,0:WIDTH 80:CLS
10 I!=I!+.1:J#=J#+.1#:LOCATE 1,1:PRINT I!;J#;(I!-J#):GOTO 10
```
I get the same results of jdoucette, the output is slow and stalls updating randomly.

To solve the issue OS side, you have to go to Task Manager, "details" tab, find pcbasicw.exe process, click the right mouse button on it and select "process affinity".
Here you can allocate HW resurces (logic CPUs) for the process. If you set 1 CPU only, the problem is gone. On some PC you can set 2 logic CPU and still solve the issue. 3 or more CPUs makes pcbasic "lag", I think due to Python's Global Interpreter Lock (GIL) feature.

Hope this was of help to you.

Regards
Stefano

**Comment by theruler** [comment] 2022-08-25 14:23
On 2.0.6 (windows) I did some timing tests with and without A$=INKEY$ and using single or multi cpu affinity:

```
10 CLS:T=TIMER
20 FOR X= 1 TO 10000
30 I!=I!+.1:J#=J#+.1#:LOCATE 1,1:PRINT I!;J#;(I!-J#)
40 NEXT
50 ? TIMER-T
```
**multi**: 18 sec (choppy output)
**single**: 35 sec (smooth output)


```
10 CLS:T=TIMER
20 FOR X= 1 TO 10000
30 I!=I!+.1:J#=J#+.1#:LOCATE 1,1:PRINT I!;J#;(I!-J#)
35 A$=INKEY$
40 NEXT
50 ? TIMER-T
```
**multi**: 87 sec (smooth output)
**single**: 122 sec (smooth output)

**Comment by robhagemans** [comment] 2022-08-25 19:22
Thanks @theruler for the metrics.

So this is actually a slightly different issue as the original issue occurred on single-core as well, and led to a complete block of screen updates. That has been resolved, however what we're seeing here is choppy updates on multi-core machines, at least under Windows. 

You are probably right that this is related to the GIL. It looks similar to this: https://www.rfk.id.au/blog/entry/a-gil-adventure-threading2/ . The analysis in that case is that when the threads execute on different cores, they race to acquire the GIL and this leads to slower performance on multiple cores than on single core. In-depth explanation in David Beazley's slides here http://www.dabeaz.com/python/UnderstandingGIL.pdf

However:
- In contrast to these links, it seems that in our case the multi-core variant runs faster, but does not update the screen as much. Which seems to imply that the engine thread simply crowds out the display thread.
- The links all discuss behaviour of Python 2, and indicate that this "GIL battle" should be improved in Python 3. I'm assuming you're running this on Python 3 - if it's the packaged Windows version it is Python 3.

The root cause of the issue I think is that (given the GIL in CPython) the display thread simply has too much CPU work to do to keep up with the engine thread, which unfortunately takes rather big changes to address and is something I'd defer until we have better test coverage. 

It may be possible to work around the issue by explicitly setting the affinity from the code - however for some reason `os.sched_setaffinity` is only available on Unix so this likely requires linking this thing in `kernel32.dll`: https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setprocessaffinitymask

**Comment by robhagemans** [comment] 2022-08-25 19:40
Further update 
- this is not Windows specific but also occurs on Linux (not tested on Mac but I assume it will occur as well)
- the issue only occurs in Python 3, not in Python 2.

For reference, on Linux, these are "smooth":

    python2 ./run-pcbasic.py update.bas 
    taskset -c 0 python3 ./run-pcbasic.py update.bas

while this is "choppy":

    python3 ./run-pcbasic.py update.bas

Here, `update.bas` is the two-line program above at  https://github.com/robhagemans/pcbasic/issues/166#issuecomment-1225707565

**Comment by theruler** [comment] 2022-08-25 21:26
> I'm assuming you're running this on Python 3 - if it's the packaged Windows version it is Python 3.

correct.

**Comment by theruler** [comment] 2022-08-29 07:58
You've fixed it!
with your changes single and multi cpu speed are almost identical and the CPU load is back to normal.
multi 24.39 sec
![single](https://user-images.githubusercontent.com/777458/187152704-0aea4364-7f4f-4a73-b765-de8f47c9502b.jpg)
single 23.75 sec



The output by the way features pseudo-random accelerations. You can tell looking at the counter running.

I think it is worth paste your code comment in eventcycle.py:

        # what I think is happening here is that the sdl2 interface thread,
        # in its loop to process a single queue item, calls C library functions
        # which do not need the GIL. so it releases it. this allows the engine thread to pick up
        # and produce more work for the interface thread. sleep(0) does not wait but it does release
        # the GIL back, so we need a few sleep(0) calls to allow the interface to get through
        # individual items.
        # this would not be a problem if the interface thread did not need the GIL at all
        # (perhaps with numba, nuitka, cython, pypy or jython)
        # but note that the video queue is a Python object so may require the GIL
        # or if it held the GIL for a full cycle
        # wait to for the queue to drain if it excceds a threshold value
        # this allows the interface to catch up with video updates


I've tried to run the code deleting the lib folder where SDL2.DLL and SDL2_gfx.DLL are, and it run anyways.
Does this mean that SDL is not loaded or pcbasic is just using SDL in other PATH folder?

here is the warnings:

c:\Intel\pcbasic-master>python run-pcbasic.py
[09:49:05.0646] WARNING: Failed to load library sdl2: could not find any library for SDL2 (looked in paths: ('C:\\Intel\\pcbasic-master\\pcbasic\\lib',))
[09:49:05.0646] WARNING: Failed to load library sdl2_gfx: could not find any library for SDL2_gfx (looked in paths: ('C:\\Intel\\pcbasic-master\\pcbasic\\lib',))
[09:49:05.0646] INFO: Could not initialise video plugin `sdl2`: Module `sdl2` not found
[09:49:05.0646] WARNING: The `pygame` interface is deprecated, please use the `graphical` interface instead.
[09:49:05.0646] INFO: Could not initialise video plugin `pygame`: Module `pygame` not found
[09:49:05.0662] WARNING: Failed to load library sdl2: could not find any library for SDL2 (looked in paths: ('C:\\Intel\\pcbasic-master\\pcbasic\\lib',))
[09:49:05.0662] WARNING: Failed to load library sdl2_gfx: could not find any library for SDL2_gfx (looked in paths: ('C:\\Intel\\pcbasic-master\\pcbasic\\lib',))
[09:49:05.0662] INFO: Could not initialise audio plugin `ansi`: Module `sdl2` not found

**Comment by robhagemans** [comment] 2022-08-29 09:25
By the looks of that log, PC-BASIC would have ran in text mode without using SDL2. You'd notice though, it looks rather different, running in the command prompt window rather than opening a window of its own.

**Comment by robhagemans** [comment] 2023-03-16 07:29
Hi, I'm afraid I can't give an ETA, this is purely a project I work on in
spare time.

I've been meaning to spend a bit of time on it for a while but have been
busy with other projects and of course the day job

**Closed** 2023-04-02 19:41 UTC
Labels: complex
