### ISSUE TITLE
crash report after a program break followed by listing a single line

### ISSUE THREAD

**Issue by moasislv** [robhagemans/pcbasic#225] opened 2023-07-22 18:50 UTC
## Bug report

**Problem**

**Steps**

1.  after a brief run i did a control c
2. I then listed line 50
3. the crash report popped up
4.  
5.  

**Program**

**Crash log**

**Notes**

PC-BASIC version:  
Operating system version:

**Comment by robhagemans** [comment] 2023-07-24 09:49
Thanks for reporting the crash. Unfortunately with the information you provide I cannot reproduce this, which means there ius no way for me to investigate what the problem is or how to resolve it.

Please can you share the listing of the program and the crash report, which might help investigate this crash.

**Comment by robhagemans** [comment] 2023-09-05 08:32
Closing as unable to reproduce without further information

**Closed by robhagemans** 2023-09-05 08:32 UTC
Labels: invalid
